// Generated by CoffeeScript 1.8.0
(function() {
  var arr, fs, path;

  fs = require('fs');

  path = require('path');

  arr = [];

  module.exports = function(dir, filterStr, callback) {
    return fs.readdir(dir, function(err, files) {
      var file, _i, _len;
      if (err) {
        return callback(err);
      }
      for (_i = 0, _len = files.length; _i < _len; _i++) {
        file = files[_i];
        if (path.extname(file) === "." + filterStr) {
          arr.push(file);
        }
      }
      return callback(null, arr);
    });
  };

}).call(this);
