// Generated by CoffeeScript 1.8.0

/*xcercise 5: Filtered LS */


/*
fs = require('fs')
path = require('path')

fs.readdir process.argv[2], (err,files) -> (console.log file if (path.extname(file) == "." + process.argv[3])) for file in files
 */


/*Excercise 6: Make It Modular */

(function() {
  var dir, extension, mymodule;

  mymodule = require('./mymodule');

  dir = process.argv[2];

  extension = process.argv[3];

  mymodule(dir, extension, function(err, files) {
    var file, _i, _len, _results;
    if (err) {
      console.error("error", err);
    }
    _results = [];
    for (_i = 0, _len = files.length; _i < _len; _i++) {
      file = files[_i];
      _results.push(console.log(file));
    }
    return _results;
  });

}).call(this);
