// Generated by CoffeeScript 1.8.0
(function() {
  var fs, path;

  fs = require('fs');

  path = require('path');

  fs.readdir(process.argv[2], function(err, files) {
    var file, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = files.length; _i < _len; _i++) {
      file = files[_i];
      _results.push(path.extname(file) === "." + process.argv[3] ? console.log(file) : void 0);
    }
    return _results;
  });

}).call(this);
